-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Sep 08, 2021 at 04:33 PM
-- Server version: 10.4.20-MariaDB
-- PHP Version: 8.0.9

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `companies_db`
--

-- --------------------------------------------------------

--
-- Table structure for table `companies`
--

CREATE TABLE `companies` (
  `company_id` int(11) NOT NULL,
  `company_title` char(255) NOT NULL,
  `company_brief` text NOT NULL,
  `company_detail` text NOT NULL,
  `company_location` char(255) NOT NULL,
  `company_branches` text NOT NULL,
  `company_employees` char(255) NOT NULL,
  `company_annual_sales` char(255) NOT NULL,
  `company_price` char(255) NOT NULL,
  `company_entry_date` date DEFAULT NULL,
  `company_source` char(255) NOT NULL,
  `company_domain` char(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `companies`
--

INSERT INTO `companies` (`company_id`, `company_title`, `company_brief`, `company_detail`, `company_location`, `company_branches`, `company_employees`, `company_annual_sales`, `company_price`, `company_entry_date`, `company_source`, `company_domain`) VALUES
(1248, 'Schreinerei zu verkaufen inkl. Maschinen', 'Schreinerei (laufender Betrieb inkl. Maschinen), in angemieteter Produktionshalle zu verkaufen.', '<p>Nutzfläche 400 m².\n</p><p></p><p>Miete € 1.600,- + NK sind bei erfolgreicher Übernahme mit dem Vermieter zu klären.\n</p><p></p><p>\n</p><p></p><p>1 x Lackierraum\n</p><p></p><p>1 x Showroom mit Fenster\n</p><p></p><p>1 x Büro ohne Fenster mit separatem Eingang\n</p><p></p><p>1 x kleiner Pausenraum ohne Fenster\n</p><p></p><p>1 x kleine Küche\n</p><p></p><p>2 x Toilettenräume inkl. Waschbecken (Privat und Gast)\n</p><p></p><p>2 x große Rolltore (manueller Betrieb, eins davon mit Eingangstür)\n</p><p></p><p>4 x PKW Stellplätze vorhanden</p>', 'Hessen > Darmstadt > Main-Kinzig-Kreis', '<ul><li>Handwerk > Ausbaugewerbe > Tischler</li></ul>', 'bis 5 Beschäftigte', 'über 50 - 250 Tsd. Euro', 'über 250 - 500 Tsd. Euro', '2021-09-08', 'https://www.nexxt-change.org/DE/Verkaufsangebot/Detailseite/detailseite_jsp.html;jsessionid=26A80094E2FF42B0EF8DD4DC632F2020?cms_adId=178798', 'https://www.nexxt-change.org'),
(1249, 'Erfolgreiches Floristik-Geschäft aus Altersgründen zu verkaufen', 'Floristik-Geschäft mit treuer Kundschaft in zentraler Innenstadtlage aus Altersgründen abzugeben.', '<p>Floristik-Geschäft mit treuem Kundenstamm in zentraler Innenstadtlage mit Parkmöglichkeiten im Raum Anhalt sucht altersbedingt einen Nachfolger.\n</p><p></p><p> \n</p><p></p><p>Das Geschäft umfasst ca. 50 qm. Davon sind 35 qm dem Verkaufsraum und ca. 15 qm den Nebenräumen zuzuschreiben. Die gesamte Ladeneinrichtung inkl. Kühlzelle wird übergeben. \n</p><p></p><p>\n</p><p></p><p>Der bisherige Inhaber steht in der Anlaufphase der Nachfolge gern unterstützend zur Seite.\n</p><p></p>', 'Sachsen-Anhalt > Sachsen-Anhalt', '<ul><li>Handel > Sonstige</li><li>Dienstleistung > Sonstige Dienstleistungen > Kreative, künstlerische und unterhaltende Tätigkeiten</li><li>Kunst, Unterhaltung und Erholung > Kreative, künstlerische und unterhaltende Tätigkeiten</li><li>Handel > Einzelhandel > Holz, Möbel und Zubehör</li></ul>', 'bis 5 Beschäftigte', 'über 50 - 250 Tsd. Euro', 'Nicht veröffentlicht', '2021-09-08', 'https://www.nexxt-change.org/DE/Verkaufsangebot/Detailseite/detailseite_jsp.html;jsessionid=26A80094E2FF42B0EF8DD4DC632F2020?cms_adId=178803', 'https://www.nexxt-change.org'),
(1250, 'Tischlerei im Kreis Lippe abzugeben', 'Kleine Tischlerei mit Spezialisierung auf Möbelfertigung, Restaurierung und Antiquitäten sucht altersbedingt in den kommenden 2-3 Jahren einen Nachfolger.', '<p>Die voll ausgestattete Werkstatt (mit Lackierraum) befindet sich im Kreis Lippe. Der Inhaber fertigt individuelle Möbel/Einrichtungen nach Maß und restauriert alte Möbel. Seit den 1990er Jahren existiert die Werkstatt und der Inhaber hat sich im Laufe der Jahre einen Namen gemacht. Ein Nachfolger kann sich selbstverständlich neu ausrichten, die Werkstatt mit Einrichtung ist vorhanden.“</p>', 'Nordrhein-Westfalen > Detmold > Lippe', '<ul><li>Handwerk > Ausbaugewerbe > Tischler</li></ul>', 'bis 5 Beschäftigte', 'über 50 - 250 Tsd. Euro', 'über 50 - 250 Tsd. Euro', '2021-09-08', 'https://www.nexxt-change.org/DE/Verkaufsangebot/Detailseite/detailseite_jsp.html;jsessionid=26A80094E2FF42B0EF8DD4DC632F2020?cms_adId=178804', 'https://www.nexxt-change.org'),
(1251, '184383 Gut positionierter Hygienedienstleister sucht Nachfolger', 'Unterhalts- und Industriereinigung', '<p>Unternehmensgegenstand:\n</p><p></p><p>Das Unternehmen ist Fachbetrieb für die Unterhaltsreinigung im Innen- und Außenbereich, für die Industriereinigung von Maschinen, Anlagen und Hallen und für die Foodreinigung. Die Geschäftsbereiche Personaldienstleistungen, Hausmeisterservice und Nacharbeit runden das Portfolio ab. Der Meisterbetrieb ist DIN ISO zertifiziert, patentiert und wurde mehrfach ausgezeichnet. \n</p><p></p><p>Historie:\n</p><p></p><p>Die Firma ist seit über 10 Jahren mit großem Erfolg am Markt tätig.\n</p><p></p><p>Mitarbeiter:\n</p><p></p><p>Operativ stehen dem Geschäftsführer neben einem Betriebsleiter, einem Bereichsleiter und einem Disponenten zehn Objektleiter sowie rund 300 Reinigungskräfte zur Verfügung. In der Verwaltung wird er von fünf Mitarbeitern unterstützt.\n</p><p></p><p>Kunden:\n</p><p></p><p>Die rund 50 langjährigen Stammkunden kommen aus der Lebensmittelbranche, dem Bereich Automotive und aus dem\n</p><p></p><p>Dienstleistungsbereich.\n</p><p></p><p>Unternehmenszahlen:\n</p><p></p><p>In den vergangenen drei Jahren wurde ein Umsatz von durchschnittlich rund 3,6 Mio. Euro pro Jahr erzielt. \n</p><p></p><p>Entwicklungspotenzial:\n</p><p></p><p>Durch die gute Marktpositionierung ist mit einem strategischenPartner ein schnelles Wachstum möglich</p>', 'Rheinland-Pfalz', '<ul><li>Dienstleistung > Sonstige Dienstleistungen</li></ul>', 'über 100 Beschäftigte', 'über 2,5 Mio. Euro', 'Nicht veröffentlicht', '2021-09-08', 'https://www.nexxt-change.org/DE/Verkaufsangebot/Detailseite/detailseite_jsp.html;jsessionid=26A80094E2FF42B0EF8DD4DC632F2020?cms_adId=178802', 'https://www.nexxt-change.org'),
(1252, 'EINZELHANDEL  DEKORATION & WOHNACCESSOIRES', 'NACHFOLGER GESUCHT – ab sofort zu    KAUFEN / PACHTEN!\r\nKleines Ladengeschäft für Wohnaccessoires, Heimtextil und Dekoration', '<p>Süßer, kleiner Deko- Shop in Shop im Vintage- Style.\n</p><p></p><p>Unsere Dekorationsartikel, Heimtextilen und Wohnaccessoires sind von namhaften Marken und mit liebe zusammengestellt.\n</p><p></p><p>\n</p><p></p><p>STANDORT: Altenstadt Mitte, direkt an der Memminger Straße (Orts Hauptdurchfahrtstraße)\n</p><p></p><p>\n</p><p></p><p>RÄUMLICHKEITEN: gesamt über 50qm\n</p><p></p><p>LAGER / WERKSTATT: ca. 12qm\n</p><p></p><p>\n</p><p></p><p>\n</p><p></p><p>Das Ladengeschäft ist voll ausgestattet mit dem gesamten Inventar, Regale, Schränke \n</p><p></p><p>inkl. Warenbestand -aktuelle Standartware – Saisonware \n</p><p></p><p>\n</p><p></p><p>Alle weiteren Vereinbarungen auf Verhandlungsbasis.\n</p><p></p>', 'Bayern > Schwaben > Neu-Ulm', '<ul><li>Handel > Einzelhandel > Sonstige</li></ul>', 'Nicht veröffentlicht', 'bis 50 Tsd. Euro', 'bis 50 Tsd. Euro', '2021-09-08', 'https://www.nexxt-change.org/DE/Verkaufsangebot/Detailseite/detailseite_jsp.html;jsessionid=26A80094E2FF42B0EF8DD4DC632F2020?cms_adId=178785', 'https://www.nexxt-change.org'),
(1253, 'FACHHANDEL mit GESCHENKMANUFAKTUR  FEINKOST – TEE – DEKORATION & WOHNACCESSOIRES', 'NACHFOLGER GESUCHT -ab sofort zu  KAUFEN / PACHTEN!\r\nGut gehendes Fachgeschäft in Innenstadtlage \r\nvoll ausgestattet, gut ausgebildeter Belegschaft und treuem Kundenstamm sucht einen Nachfolger.', '<p>Wunderschönes Fachgeschäft mit über 100 Teesorten einer Spirituosen & Likör sowie einer Essig & Öl -BAR mit Abfüllservice, 2 Kühltheken gefüllt mit den unverkennbaren LANWEHR- Pralinen, unsere Dekorationsartikel und Wohnaccessoires sind von namhaften Herstellern und mit liebe zusammengestellt, rundum alles so ganz nach dem Motto “geschmackvoll das Leben genießen“\n</p><p></p><p>Seit über 20 Jahren sind wir die Anlaufstelle für besondere Geschenke, in der Geschenkmanufaktur wird alles mit liebe und individuell verpackt ob zum Geburtstag, zur Hochzeit, zum Abschied, als kleines Dankeschön, aber auch im großen Stil, zum Firmen- Jubiläum, Kundendank und Weihnachts- Jahresabschluss . . . \n</p><p></p><p>\n</p><p></p><p>STANDORT: Vöhringens Mitte, direkt an der Ulmer Straße (Orts Hauptdurchfahrtstraße)\n</p><p></p><p>\n</p><p></p><p>RÄUMLICHKEITEN: gesamt über 200qm\n</p><p></p><p>LAGER / BÜRO: ca. 30 – 40qm\n</p><p></p><p>LADENFLÄCHE: ca. 160 – 170qm\n</p><p></p><p>KELLER: ca. 25 - 30qm\n</p><p></p><p>PERSONAL: 2 Teilzeit -Fachkräfte – 2 Minijobler – 1 Azubi \n</p><p></p><p>\n</p><p></p><p>\n</p><p></p><p>Das Ladengeschäft ist voll ausgestattet mit dem gesamten Inventar, Regale, Schränke Theken, 3 – 5 Liter Amphoren in der Abfüllbar für Essig & Öl sowie Spirituosen & Liköre, Kühlschrank und 2 Theken für Pralinen, 1 – 2 kg Teedosen (ca.150 Stück) \n</p><p></p><p>2 Abfüllwaagen ( geeicht: Stand Juni 2021)\n</p><p></p><p>inkl. Warenbestand -aktuelle Standartware – Saisonware \n</p><p></p><p>\n</p><p></p><p>Alle weiteren Vereinbarungen auf Verhandlungsbasis.\n</p><p></p>', 'Bayern > Schwaben > Neu-Ulm', '<ul><li>Handel > Einzelhandel > Nahrungs- und Genussmitteln, Getränken und Tabakwaren</li></ul>', 'bis 5 Beschäftigte', 'über 50 - 250 Tsd. Euro', 'über 50 - 250 Tsd. Euro', '2021-09-08', 'https://www.nexxt-change.org/DE/Verkaufsangebot/Detailseite/detailseite_jsp.html;jsessionid=26A80094E2FF42B0EF8DD4DC632F2020?cms_adId=178784', 'https://www.nexxt-change.org'),
(1254, 'Starke Regionalmarke für Textilien und maritime Accessoires zu verkaufen', 'Angeboten wird eine starke, sympathisch besetzte Marke für hochwertige maritime Textilien und Accessoires. Die Marke bietet enormes Potenzial.  Markenrechte und Bestände werden zum Verkauf angeboten.', '<p>Die Ursprünge der Marke liegen in Hamburg: Hier entwickelte der Mehrheitsgesellschafter die Marke und startete mit dem Verkauf von Polos und T-Shirts auf Messen und Märkten. Die Resonanz auf das Label und ihre Symbolfigur war von Beginn an hervorragend, so dass der Gründer sich entschloss, das Label zu professionalisieren. So kamen zwei weitere Partner an Bord. Einer davon, über Jahrzehnte in Asien ansässig, ist dort Inhaber eines Unternehmens für Textilveredelung und verfügt über herausragende Kontakte zu weltweiten Textil- und Accessoire – Produktionsbetrieben. So wurde gemeinsam eine maritime Erlebniswelt entwickelt, deren Basis qualitativ hochwertige Produkte sind. Das Design der Textilien ist klassisch und zeitlos und unterliegt keinen Modeströmungen. Das Produktportfolio umfasst u.a. T-Shirts, Polohemden, Hemden, Strickmützen, Elbsegler, Seglermützen, Kapitänsmäntel, Strickjacken, Halstücher, wasserdichte Seesäcke und weitere Accessoires. Die Marke ist erweiterbar auf jegliche Art maritim gebrandeter Artikel wie Taschen, Keramikwaren, Dekorationsobjekte und Lebensmittel wie Kakao, Kaffee, Tee oder Gewürze. Dazu kommt eine attraktive textile Kinderkollektion. Auf Grund der Tatsache, dass alle drei Inhaber hauptberuflich in anderen Bereichen unterwegs sind, fehlte es final an den personellen Kapazitäten, das große Potential der Marke kontinuierlich weiterzuentwickeln. Daraus resultierte der Beschluss, nunmehr Markenrechte und Bestände zu veräußern. Idealerweise ist der Erwerber bereits im Textil -und Accessoirevertrieb aktiv und kann hier sein Portfolio um eine starke Marke erweitern. Einer der Mitinhaber steht bei Interesse auch weiterhin für das Produktsourcing und/oder als Minderheitsgesellschafter zur Verfügung. \n</p><p></p><p>\n</p><p></p>', 'Hamburg > Hamburg > Hamburg', '<ul><li>Handel</li></ul>', 'bis 5 Beschäftigte', 'Nicht veröffentlicht', 'über 50 - 250 Tsd. Euro', '2021-09-08', 'https://www.nexxt-change.org/DE/Verkaufsangebot/Detailseite/detailseite_jsp.html;jsessionid=26A80094E2FF42B0EF8DD4DC632F2020?cms_adId=178786', 'https://www.nexxt-change.org'),
(1255, 'Nachfolger für Unternehmen im technischen Sonnenschutz', 'Das Unternehmen ist im Bereich technischer Sonnenschutz für  Ausstattung von Neubauten  (öffentl. und gewerbl. Gebäude und Wohnanlagen) und für die energetische Sanierung im Objektbereich tätig.', '<p>Das Unternehmen rüstet Gebäude mit Sonnenschutzanlagen aus, einschließlich Planung, Beschaffung, Finanzierung und Montage. Die Firmengründung erfolgte 1982 in München. Der Verkauf ist aus Altersgründen vorgesehen. \n</p><p></p><p>\n</p><p></p><p>Das Unternehmen arbeitet seit Jahrzehnten mit Herstellern zusammen. Die Zusammenarbeit ist zum Teil vertraglich geregelt. Die Bearbeitung erfolgt mit 3 festen Mitarbeitern und einem Pool von ca. 10 freien Monteuren. Das Unternehmen befindet sich in einem gemieteten Gebäude im Norden von München mit 1 km Anfahrt zur Bundesautobahn mit Büros, Lager, Werkstatt und einem Ausstellraum.\n</p><p></p><p>Das Kundenpotential ist seit über 40 Jahren gewachsen und kann noch deutlich gesteigert werden. Das Unternehmen bietet eine individuelle cad-gestützte Planung und Umsetzung von gewerblichen Sonderlösungen. Durch die Klimaprobleme werden Sonnenschutzanlagen als passive Energiequellen an Bedeutung enorm gewinnen und einen notwendigen Faktor bei Neubauten und energetischen Sanierungen darstellen. \n</p><p></p>', 'Bayern > Oberbayern > München, Landkreis', '<ul><li>Baugewerbe > Spezialisierte Bautätigkeiten</li></ul>', 'bis 5 Beschäftigte', 'über 500 Tsd. - 2,5 Mio. Euro', 'über 250 - 500 Tsd. Euro', '2021-09-08', 'https://www.nexxt-change.org/DE/Verkaufsangebot/Detailseite/detailseite_jsp.html;jsessionid=26A80094E2FF42B0EF8DD4DC632F2020?cms_adId=178632', 'https://www.nexxt-change.org'),
(1256, 'Etablierter Onlinehandel mit Haushaltsgeräten mit eigener Marke abzugeben', 'Es handelt sich um einen Onlineversand von Haushaltsgeräten und lukrativen Zubehörartikeln mit International geschützter Marke,  eigenem Webshop, Amazon Ebay etc. sowie eigener Logistik und Technik', '<p>Das Unternehmen wurde 1998 gegründet und hat sich seither stehts weiter entwickelt. Die Fertigung der Produkte findet im wesentlichen in Asien statt. Durch den Verkauf von Luftreinigern seit rund 20 Jahren hat sich ein interessantes Folgegeschäft für Filter und Zubehörartikel mit guten Margen entwickelt. Der wesentliche Vertriebsfokus ist Deutschland und Österreich, wobei auch Italien und Frankreich zu den Absatzmärkten gehört. Neben Amazon und Ebay werden die Produkte auch bei zahlreichen weiteren Plattformen angeboten. Auch ein eigener Webshop mit rund 15000 registrieren Kunden ist vorhanden.\n</p><p></p><p>\n</p><p></p><p>Das Unternehmen verfügt über ein Produktionsnetzwerk in Asien mit langjährgigen Lieferantenbeziehungen . Auch in Zeiten von Corona kann die Qualitätssicherung in China durch langjährige Partner vor Ort sichergestellt werden. Die Umsätze belaufen sich Jährlich auf 2-3 Mio EUR bei einem Vorsteuerergebnis zwischen 300 und 500 TEUR + ca. 100 TEUR Geschäftsführergehalt. In den letzten beiden Jahren ist das Zubehörgeschäft besonders stark gewachsen was die Margen stetig verbessert hat.\n</p><p></p><p>\n</p><p></p><p>Das Unternehmen hat 4 langjährige Mitarbeiter. Es verfügt über ein Betriebsgelände mit ca. 1300m² Lagerfläche und 200 m² Bürofläche und 400 m² Servicewerkstatt. Die Immobilie befindet sich im Eigentum der GmbH und kann mit übernommen werden muss aber nicht. Auch ein Mietmodell ist denkbar. Die Eingangslogistik ist extern vergeben die Ausgangslogistik wird selbst durchgeführt.</p>', 'Bayern > Niederbayern > Dingolfing-Landau', '<ul><li>Handel > Online-Handel</li></ul>', 'bis 5 Beschäftigte', 'über 2,5 Mio. Euro', 'über 2,5 Mio. Euro', '2021-09-08', 'https://www.nexxt-change.org/DE/Verkaufsangebot/Detailseite/detailseite_jsp.html;jsessionid=26A80094E2FF42B0EF8DD4DC632F2020?cms_adId=178779', 'https://www.nexxt-change.org'),
(1257, 'Subway Bruchsal zu verkaufen', 'Wir verkaufen unser Subway in Bruchsal / Kammerforststraße aus familären Gründen.', '<p>Das umsatzstarke Restaurant befindet sich in der Nähe der Autobahn A5 und der Bundesstraße B3 sowie der Durchfahrtsstraße von Bruchsal nach Karlsdorf-Neuthard. Es ist im Gewerbegebiet Bruchsal \"Am Mantel\" in unmittelbarem Umfeld eines großen Technikmarktes, eines großen Baumarktes, mehrerer Möbelmärkte sowie zahlreicher Fach- und Einzelhandelsgeschäfte angesiedelt. \n</p><p></p><p>\n</p><p></p><p>Das Restaurant besitzt einen großen Innen- und Außenbereich mit Terrasse. Das Unternehmen ist sowohl für Gastroprofis als auch für Quer- oder Neueinsteiger geeignet.\n</p><p></p><p>\n</p><p></p><p>Durch die Weltmarke Subway ist eine ständige Weiterentwicklung des Restaurants und die Unterstützung des Unternehmers gewährleistet. Nutzen Sie die Gelegenheit und führen Sie Ihr eigenes Restaurant.\n</p><p></p><p>\n</p><p></p>', 'Baden-Württemberg > Karlsruhe > Karlsruhe, Landkreis', '<ul><li>Gastgewerbe > Gastronomie</li></ul>', 'bis 5 Beschäftigte', 'über 50 - 250 Tsd. Euro', 'über 50 - 250 Tsd. Euro', '2021-09-08', 'https://www.nexxt-change.org/DE/Verkaufsangebot/Detailseite/detailseite_jsp.html;jsessionid=26A80094E2FF42B0EF8DD4DC632F2020?cms_adId=178790', 'https://www.nexxt-change.org'),
(1258, 'Projekt KAFKA – Design- und Mediendienstleister aus Süddeutschland', 'Wir vertreten exklusiv die Gesellschafter eines breit aufgestellten Design- und Mediendienstleisters aus Süddeutschland bei der Veräußerung von bis zu 100 % der Unternehmensanteile.\r\nKAFKA ist ein Dienstleister mit zwei synergetisch verbundenen Geschäftsfeldern. Als Anbieter von Geschenkartikeln jeder Art designt und fertigt die Gesellschaft eine Vielzahl individuell…', '<p>\r\n \r\n Wir vertreten exklusiv die Gesellschafter eines breit aufgestellten Design- und Mediendienstleisters aus Süddeutschland bei der Veräußerung von bis zu 100 % der Unternehmensanteile.</p><p></p><p>\r\nKAFKA ist ein Dienstleister mit zwei synergetisch verbundenen Geschäftsfeldern. Als Anbieter von Geschenkartikeln jeder Art designt und fertigt die Gesellschaft eine Vielzahl individuell gestalteter Produkte. Die Auftraggeber schätzen insbesondere die Flexibilität in der Auftragsdurchführung sowie die Exklusivität und Emotionalität der Produkte.</p><p></p><p>\r\nZudem fungiert die Gesellschaft als Fulfillmentdienstleister für im deutschsprachigen Raum bekannte Verlage und übernimmt die Abwicklung der operativen Tätigkeiten rund um deren Online-Shops.</p><p></p><p>\r\nEin diversifizierter Kundenstamm sorgt für ein geringes Maß an Kundenabhängigkeit. Langjährige, partnerschaftliche Beziehungen zu Lieferanten und Dienstleistern gewährleisten zu jeder Zeit eine hochwertige Ausführungsqualität.</p><p></p><p>\r\nDie etablierte Marke, ein breites Partnernetzwerk und fixe interne Strukturen bieten vielseitige Wachstumsmöglichkeiten für einen Nachfolger.</p><p></p><p>\r\nEckdaten: 80 % wiederkehrende Kunden; Gesellschafter steht für Übergangsphase bereit.</p><p></p><p>\r\n\r\n \r\n </p>', 'Süd Deutschland', '<ul><li>Andere Branchen</li></ul>', '10', '2.000.000 €', 'Keine Angaben', NULL, 'https://www.dub.de/kaufangebot/9645/projekt-kafka-design-und-mediendienstleister-aus-sueddeutschland/?cHash=ae61d852574571da0329f7665f1c91ea', 'https://www.dub.de'),
(1259, 'Industrietechnik & -anlagenbau', 'Nachhaltig ertragreiches und wachsendes Industrieanlagenbau- und Industrieservice-Unternehmen mit äußerst guter Marktposition.\r\n\r\nDas Unternehmen konnte sich innerhalb kürzester Zeit einen sehr guten Ruf in der Branche aufbauen und verfügt über ein signifikantes Alleinstellungsmerkmal, das die Basis für ein weiteres nachhaltiges Wachstum darstellt.', '<p>\r\n \r\n Nachhaltig ertragreiches und wachsendes Industrieanlagenbau- und Industrieservice-Unternehmen mit äußerst guter Marktposition.</p><p></p><p>\r\n</p><p></p><p>\r\nDas Unternehmen konnte sich innerhalb kürzester Zeit einen sehr guten Ruf in der Branche aufbauen und verfügt über ein signifikantes Alleinstellungsmerkmal, das die Basis für ein weiteres nachhaltiges Wachstum darstellt.</p><p></p><p>\r\n\r\n \r\n </p>', 'Keine Angaben Österreich', '<ul><li>Maschinenbauer / Anlagenbauer</li></ul>', 'Keine Angaben', '2.800.000 €', '7.400.000 €', NULL, 'https://www.dub.de/kaufangebot/9972/industrietechnik-anlagenbau/?cHash=49835ee437c1ec167bc0ad8c8f4553a9', 'https://www.dub.de'),
(1260, 'Produktion und Entwicklung von Magnesiumbauteilen für Automotive-Industrie', 'Aufbau einer Entwicklung und Produktion von Magnesiumbauteilen für die Automotiv-Industrie – vor Ort in Deutschland für unsere Kunden in Europa.\r\n\r\nEinzigartige hochtechnologische und innovative Magnesiumlegierungen und Herstellungsverfahren, die über mehr als 12 Jahre kontinuierliche und fortlaufende Forschung und Entwicklung in Indien entwickelt wurden.\r\n\r…', '<p>\r\n \r\n Aufbau einer Entwicklung und Produktion von Magnesiumbauteilen für die Automotiv-Industrie – vor Ort in Deutschland für unsere Kunden in Europa.</p><p></p><p>\r\n</p><p></p><p>\r\nEinzigartige hochtechnologische und innovative Magnesiumlegierungen und Herstellungsverfahren, die über mehr als 12 Jahre kontinuierliche und fortlaufende Forschung und Entwicklung in Indien entwickelt wurden.</p><p></p><p>\r\n</p><p></p><p>\r\nAlleinstellungsmerkmal:</p><p></p><p>\r\nAls einer der wenigen weltweit operierenden Unternehmen im Bereich von Magnesiumbauteilen und –baugruppen bieten wir alles aus einer Hand an - vom Entwurf über Herstellung und Bearbeitung bis zur Beschichtung. </p><p></p><p>\r\nMit den Erfahrungen von über einem Jahrzehnt in Forschung und Innovation wurde die Technologie immer weiterentwickelt, so dass Synergien in Produktqualität und Kosteneffizienz für unsere Kunden angeboten werden können.</p><p></p><p>\r\nMagnesium, das auch als das \"grüne Metall des 21. Jahrhunderts\" bezeichnet wird, ist umweltfreundlich und gilt als das leichteste aller Strukturmetalle.</p><p></p><p>\r\nUSP 1: Optimierung der Magnesium-Legierungen hinsichtlich des entsprechenden Anwendungsfalles </p><p></p><p>\r\nUSP 2: Prozess Know-how von Magnesium in der Produktion</p><p></p><p>\r\n</p><p></p><p>\r\n\r\n \r\n </p>', '85 Deutschland', '<ul><li>Fahrzeugbauer</li><li>Sonstiges KFZ / Auto</li><li>Großhandel mit sonstigen Maschinen / Ausrüstungen / Zubehör</li></ul>', '7', '2,51 - 5,0 Mio. €', '1.500.000 €', NULL, 'https://www.dub.de/kaufangebot/9970/produktion-und-entwicklung-von-magnesiumbauteilen-fuer-automotive-industrie/?cHash=0c734e5b2d42fccd7d9c9ba216281368', 'https://www.dub.de'),
(1261, 'Etablierte Marke im Bereich der funktionalen Baby-, Damen- sowie Badebekleidung', 'Zum Verkauf stehen 100% der Anteile eines in 2012 gegründeten Anbieters für funktionale Bekleidung, insbesondere für Babys, Kleinkinder, Damen sowie Bademode. Das Unternehmen vertreibt ca. 400 Produkte unter drei Marken hauptsächlich auf dem Marktplatz von Amazon Deutschland. Das Umsatzwachstum zwischen 2018 und 2020 betrug ca. 29% (CAGR).', '<p>\r\n \r\n Zum Verkauf stehen 100% der Anteile eines in 2012 gegründeten Anbieters für funktionale Bekleidung, insbesondere für Babys, Kleinkinder, Damen sowie Bademode. Das Unternehmen vertreibt ca. 400 Produkte unter drei Marken hauptsächlich auf dem Marktplatz von Amazon Deutschland. Das Umsatzwachstum zwischen 2018 und 2020 betrug ca. 29% (CAGR).\r\n \r\n </p>', 'Ost Deutschland', '<ul><li>Online Handel / Online Shop</li><li>Textilhersteller / Bekleidung / Boutique</li></ul>', 'Keine Angaben', '9.505.479 €', '5.900.000 €', NULL, 'https://www.dub.de/kaufangebot/9968/etablierte-marke-im-bereich-der-funktionalen-baby-damen-sowie-badebekleidung/?cHash=320e8738e9dfa2aa12fdccb0b6c1e6f6', 'https://www.dub.de'),
(1262, 'Restaurant mit bester Lage direkt am Deich sucht einen Käufer', 'Suchen Sie ein Spitzenrestaurant - demnächst im Raum Cuxhaven zu verkaufen\r\nEin direkt (Cuxhaven /Duhnen) gelegenes Restaurant steht im Jahr 2021 bzw. 2022 zum Verkauf. Die engagierte Betreiber führt das sehr erfolgreiche Unternehmen seit vielen Jahren und konnte auch im Corona-Jahr 2020 die Serie kontinuierlicher wachsender Erträge fortsetzten.\r\nDas feste Team wird…', '<p>\r\n \r\n Suchen Sie ein Spitzenrestaurant - demnächst im Raum Cuxhaven zu verkaufen</p><p></p><p>\r\nEin direkt (Cuxhaven /Duhnen) gelegenes Restaurant steht im Jahr 2021 bzw. 2022 zum Verkauf. Die engagierte Betreiber führt das sehr erfolgreiche Unternehmen seit vielen Jahren und konnte auch im Corona-Jahr 2020 die Serie kontinuierlicher wachsender Erträge fortsetzten.</p><p></p><p>\r\nDas feste Team wird jeweils durch zusätzliche Mitarbeiter im Sommer verstärkt. Mietunterkünfte fürs Personal stehen bereit und können erworben oder angemietet werden.</p><p></p><p>\r\nEs sind nur ernstgemeinte Anfragen erwünscht. Vor Einblick in die Geschäftsunterlagen wird die Vorlage von Bonitätsunterlagen gewünscht.</p><p></p><p>\r\nBitte Anfragen an alliste@t-online.de\r\n \r\n </p>', '27476 Deutschland', '<ul><li>Restaurant / Systemgastronomie</li></ul>', 'Keine Angaben', '1.200.000 €', 'Keine Angaben', NULL, 'https://www.dub.de/kaufangebot/9477/restaurant-mit-bester-lage-direkt-am-deich-sucht-einen-kaeufer/?cHash=dfd052a2c6a51ee62bd7d663158d0b03', 'https://www.dub.de'),
(1263, 'Zulieferer für Antriebstechnik', 'Das zu veräußernde Unternehmen besteht seit 25 Jahren an seinem Standort in der Pfalz und hat sich als Zulieferer von Maschinenbauteilen mit Spezialisierung auf Dreh- und Verzahnungsteilen für den Maschinenbau in der Metallindustrie einen guten Ruf mit festen Bestandskunden, die den Hauptumsatz des Unternehmens generieren, geschaffen. Mit einigen Firmenkunden bestehen…', '<p>\r\n \r\n Das zu veräußernde Unternehmen besteht seit 25 Jahren an seinem Standort in der Pfalz und hat sich als Zulieferer von Maschinenbauteilen mit Spezialisierung auf Dreh- und Verzahnungsteilen für den Maschinenbau in der Metallindustrie einen guten Ruf mit festen Bestandskunden, die den Hauptumsatz des Unternehmens generieren, geschaffen. Mit einigen Firmenkunden bestehen Rahmenverträge. Die Produkte des Sortiments umfassen u.A. Zahnräder, Zahnstangen, Ritzel, Wellen, Schnecken und Schnecken- sowie Kettenräder. Hierbei bietet das Unternehmen seinen Kunden sowohl Komplett- als auch Teilfertigungen als Zulieferer an. Herstellung und Fertigung sind vollständig ausgelagert, so dass als Unternehmensstandort ein Homeoffice-Arbeitsplatz sowie eine Lagerfläche von rund 20 qm ausreichend sind. Der Inhaber ist Geschäftsführer und leitet als einziger Mitarbeiterin vollen Umfang alleine das Unternehmen. Um das Kundeneinzugsgebiet von rund 200 km um den Unternehmensstandort weiterhin gut betreuen zu können, sollte der Nachfolger aus der Region kommen. Die umfassende Übergabe des Unternehmensnetzwerks sowie eine qualifizierte Einarbeitung sind gewährleistet.\r\n \r\n </p>', '76 Deutschland', '<ul><li>Metallerzeuger / Metallbearbeiter / Metallerzeugnisse</li><li>Werkzeugbauer</li><li>Sonstiges produzierendes Unternehmen / Handwerksbetrieb</li><li>Andere Branchen</li></ul>', '1', '214.000 €', '132.000 €', NULL, 'https://www.dub.de/kaufangebot/9967/zulieferer-fuer-antriebstechnik/?cHash=a7e8b740f94217441b054ee1b3eff108', 'https://www.dub.de'),
(1264, 'Langjährig etablierter IT-Dienstleister', 'Langjährig am Markt etabliertes Software-Entwicklungsunternehmen mit einem klar definierten USP.\r\n\r\nDem Unternehmen ist es gelungen, sich mit einem vielseitig einsetzbaren, einfach skalierbaren Spezial-Produkt vom Mitbewerb deutlich abzugrenzen. Ein besonders wertvolles Asset stellen die hochqualifizierten, bestens ausgebildeten Mitarbeiter dar.', '<p>\r\n \r\n Langjährig am Markt etabliertes Software-Entwicklungsunternehmen mit einem klar definierten USP.</p><p></p><p>\r\n</p><p></p><p>\r\nDem Unternehmen ist es gelungen, sich mit einem vielseitig einsetzbaren, einfach skalierbaren Spezial-Produkt vom Mitbewerb deutlich abzugrenzen. Ein besonders wertvolles Asset stellen die hochqualifizierten, bestens ausgebildeten Mitarbeiter dar. </p><p></p><p>\r\n\r\n \r\n </p>', 'Keine Angaben Österreich', '<ul><li>Software / Website / Online Portal</li></ul>', '12', '1.600.000 €', '1.050.000 €', NULL, 'https://www.dub.de/kaufangebot/9966/langjaehrig-etablierter-it-dienstleister/?cHash=90211e415683c05e035bbdec379a7553', 'https://www.dub.de'),
(1265, 'D118 Hausmeisterdienst', 'Bestens eingeführtes Unternehmen aus dem FM-nahen Bereich.', '<p>\r\n \r\n Bestens eingeführtes Unternehmen aus dem FM-nahen Bereich.\r\n \r\n </p>', 'Rheinland-Pfalz Deutschland', '<ul><li>Allgemeine Dienstleistungen</li></ul>', '40', '2.000.000 €', '1.500.000 €', NULL, 'https://www.dub.de/kaufangebot/9965/d118-hausmeisterdienst/?cHash=5146df5bb1746f00ed6fa9780be13e78', 'https://www.dub.de'),
(1266, 'Projekt HORSE', 'HORSE ist ein mittelständisches Maschinenbauunternehmen aus Norddeutschland, das ein breites Produktspektrum an Anbaugeräten für die Landschaftspflege, Kommunal- und Hebetechnik sowie weitere Sondermaschinen für gewerbliche Nutzer produziert.\r\n\r\nDas etablierte Familien-Unternehmen ist bekannt für seine Markenprodukte mit hohem Qualitätsanspruch. Darüber hinaus zeichnet das…', '<p>\r\n \r\n HORSE ist ein mittelständisches Maschinenbauunternehmen aus Norddeutschland, das ein breites Produktspektrum an Anbaugeräten für die Landschaftspflege, Kommunal- und Hebetechnik sowie weitere Sondermaschinen für gewerbliche Nutzer produziert.</p><p></p><p>\r\n</p><p></p><p>\r\nDas etablierte Familien-Unternehmen ist bekannt für seine Markenprodukte mit hohem Qualitätsanspruch. Darüber hinaus zeichnet das Unternehmen prämierte, innovative Produkte und einschlägige Zertifizierungen aus. Derzeit werden 25 Mitarbeiter beschäftigt.</p><p></p><p>\r\n</p><p></p><p>\r\nNeben dem Hauptsitz gibt es einen weiteren Fertigungsstandort in unmittelbarer Nähe.\r\n \r\n </p>', 'Nord Deutschland', '<ul><li>Maschinenbauer / Anlagenbauer</li><li>Umwelttechnik / Umweltanlagen</li></ul>', '25', '3.100.000 €', 'Keine Angaben', NULL, 'https://www.dub.de/kaufangebot/9943/projekt-horse/?cHash=517717fe8723eff8bdf2270e26ed084c', 'https://www.dub.de'),
(1267, 'Strategischer Partner gesucht: SPEZIALIST FÜR ELEKTRONISCHE MESSTECHNIKSYSTEME', 'Strategischer Partner (kein MBI-Kandidat) für einen Spezialisten für elektronische Messtechnik und Systeme für vorwiegend internationale Hersteller in der gesamten DACH Region - beratungsintensiver Handel\r\n\r\n• Differenziertes Produktportfolio im Bereich Stromversorgung, Messtechnik, OEM sowie Komplettlösungen für den Kunden (Einrichtung, Wartung und Reparaturen)\r\n• Das…', '<p>\r\n \r\n Strategischer Partner (kein MBI-Kandidat) für einen Spezialisten für elektronische Messtechnik und Systeme für vorwiegend internationale Hersteller in der gesamten DACH Region - beratungsintensiver Handel</p><p></p><p>\r\n</p><p></p><p>\r\n• Differenziertes Produktportfolio im Bereich Stromversorgung, Messtechnik, OEM sowie Komplettlösungen für den Kunden (Einrichtung, Wartung und Reparaturen)</p><p></p><p>\r\n• Das Geschäftsmodell berücksichtigt bereits die aktuellen Markttrends (Medizintechnik sowie Elektromobilität)</p><p></p><p>\r\n• Team besteht aus 16 festangestellten sowie einigen freien Mitarbeitern (Hochschulniveau)</p><p></p><p>\r\n• Direkte Lieferantenverbindungen (teilweise mit Exklusivität)</p><p></p><p>\r\n• Launch eines eigenen Webshops als Handelsplattform für B2C und B2BU</p><p></p><p>\r\n• Verkauf eines schuldenfreien Unternehmens bis zu 100 % der Gesellschaftsanteile</p><p></p><p>\r\n• Vollständig saniert und neu aufgestellt</p><p></p><p>\r\n• Übergangszeitraum mit geschäftsführendem Gesellschafter für bis zu 5 Jahre möglich</p><p></p><p>\r\n• Nachhaltiger Umsatz von 4 bis 5 Mio. EUR mit einer Rohertragsmarge von bis zu 35 % p.a.\r\n \r\n </p>', 'Süd Deutschland', '<ul><li>Allgemeine Dienstleistungen</li><li>Computerhandel / IT</li><li>Sonstige Handel</li><li>Automatisierungstechnik / Mess- und Regelungstechnik</li></ul>', '16', '5.000.000 €', 'Keine Angaben', NULL, 'https://www.dub.de/kaufangebot/9963/strategischer-partner-gesucht-spezialist-fuer-elektronische-messtechniksysteme/?cHash=9f5359c0c00d5b298c3151cca8f57ff3', 'https://www.dub.de');

-- --------------------------------------------------------

--
-- Table structure for table `source_domain`
--

CREATE TABLE `source_domain` (
  `domain_id` int(11) NOT NULL,
  `domain_name` char(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `companies`
--
ALTER TABLE `companies`
  ADD PRIMARY KEY (`company_id`);

--
-- Indexes for table `source_domain`
--
ALTER TABLE `source_domain`
  ADD PRIMARY KEY (`domain_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `companies`
--
ALTER TABLE `companies`
  MODIFY `company_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1268;

--
-- AUTO_INCREMENT for table `source_domain`
--
ALTER TABLE `source_domain`
  MODIFY `domain_id` int(11) NOT NULL AUTO_INCREMENT;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
